---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: flm
spec:
  replicas: 2
  selector:
    matchLabels:
       app: swiggy
  template:
    metadata:
       labels:
         app: swiggy
    spec:
       containers:
         - name: c1
           image: shaikmustafa/dm
           ports:
             - containerPort: 80
